### ISSUE TITLE
Update the license in the source files.

### ISSUE THREAD

**Issue by kiryx** [esa/pagmo#129] opened 2015-03-18 21:04 UTC
License note in each of the header file points to the old and not maintained sourceforge repo.
It would be nice to either replace it with github urls (we can discuss here), or better just drop the urls and stick to the AUTHORS.txt when it comes to credits (which also needs updating).

**Comment by mgachhui** [comment] 2015-03-23 15:12
Hi. I'd like to take up this bug. Do I just change the sourceforge links, or drop them as you suggested?

**Comment by darioizzo** [comment] 2015-03-24 18:28
This is not a bug and was opened almost accidentally, thanks for having a look, but we will close this soon with updated headers.

**Closed** 2015-03-24 18:49 UTC
Labels: beginner
