### ISSUE TITLE
Should velocity vector (population::cur_v) be moved out of population class ?

### ISSUE THREAD

**Issue by kiryx** [esa/pagmo#109] opened 2015-03-05 17:13 UTC
Velocity vector (cur_v) is a field in population class that's specific to PSO algorithm (``algorithm::pso``, ``algorithm::nspso``, ``algorithm::mbh`` and ``algorithm::pso_generational``).

It should be moved out and stored as an field in an instance of the algorithm, and activated with a "memory" flag during construction (see covariance matrix in CMAES).

**Comment by darioizzo** [comment] 2015-03-11 12:59
This is a rather philosophical point. The decision to have the individual with a cur_v field is to allow for cooperation between PSO and other algorithms.

Some of the algorithms (DE for example) do indeed update the cur_v value (set_v) method so that when a PSO is called after it can benefit.

Also, v can contain the gradient ... so its a field that was considered useful.

Now, it is true its not used much by user, but removing it is far from being a simple issue and not necessarily better.

**Comment by darioizzo** [comment] 2015-04-30 18:18
Closing this as no discussion was actually spawned as the issue is probably not a priority

**Closed by darioizzo** 2015-04-30 18:18 UTC
Labels: enhancement, question
